#!/usr/bin/env bash
set -e

rnfile="rn.md"
tag="release-76.0"
./extract-release-notes.sh "${tag}" "${rnfile}"
hub release create --file "${rnfile}" "$tag"
tag="release-75.0.0"
./extract-release-notes.sh "${tag}" "${rnfile}"
hub release create --file "${rnfile}" "$tag"
tag="release-74.0.0"
./extract-release-notes.sh "${tag}" "${rnfile}"
hub release create --file "${rnfile}" "$tag"
tag="release-73.0.0"
./extract-release-notes.sh "${tag}" "${rnfile}"
hub release create --file "${rnfile}" "$tag"
tag="release-72.0.0"
./extract-release-notes.sh "${tag}" "${rnfile}"
hub release create --file "${rnfile}" "$tag"
tag="release-71.1.0"
./extract-release-notes.sh "${tag}" "${rnfile}"
hub release create --file "${rnfile}" "$tag"
tag="release-71.0.0"
./extract-release-notes.sh "${tag}" "${rnfile}"
hub release create --file "${rnfile}" "$tag"
