on:
  push:
    branches: [ main ]
    tags: [ "release-*" ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    # mkvtoolnix supports cross compile from linux to windows; while mingw on windows works it is not supported
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install autopoint gperf libtool-bin lzip intltool python3-mako
      - uses: actions/checkout@v3
      # mkvtoolnix-specialized fork of mxe
      # build docs declare path must be $HOME/mxe
      - run: git clone --depth 1 https://gitlab.com/mbunkus/mxe $HOME/mxe
      - run: cd $HOME/mxe
      - run: LOGFILE=/proc/$$/fd/1 ./packaging/windows/setup_cross_compilation_env.sh
        timeout-minutes: 10
      - if: failure()
        uses: actions/upload-artifact@v3
        with:
          path: /tmp/mkvtoolnix_setup_cross_compilation_env.*
      - run: rake
